name: CI

on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.4.0
      - uses: ocaml/setup-ocaml@v2.0.12
        with:
          ocaml-compiler: 5.0.0
      - name: Install dependencies
        run: opam install --deps-only -t .
      - name: Run tests
        run: opam exec -- dune runtest
