name: CI

on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.4.0

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - uses: ocaml/setup-ocaml@v2.0.12
        with:
          ocaml-compiler: 5.0.0
          dune-cache: true

      - name: Install dependencies
        run: |
          opam install --deps-only -t .
          cd test/visual_regression_test
          npm install -g odiff-bin

      - name: Run tests
        run: opam exec -- dune runtest
